{
 "title": "Crypto monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Bitcoin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current bitcoin curve",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  metric AS metric,\n  value_eur,\n  value_usd\nFROM bitcoin\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Current bitcoin curve",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT  time, value_eur, value_usd FROM bitcoin"
    }
   ]
  },
  {
   "title": "Total row in Bitcoin database",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  count(time) as NB_DATA FROM bitcoin"
    }
   ]
  },
  {
   "title": "Total row over last 24H",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  count(time) as NB_DATA FROM bitcoin where day(time)=day(now())"
    }
   ]
  },
  {
   "title": "Bitcoin stat by week",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT week(time) as NUM_SEMAINE, avg(value_eur)as Moyenne,min(value_eur) as Minimum, max(value_eur) as Maximum FROM bitcoin group by NUM_SEMAINE order by NUM_SEMAINE asc"
    }
   ]
  },
  { "title": "Ethereum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Current ethereum curve ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  metric AS metric,\n  value_eur,\n  value_usd\nFROM ethereum\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Current ethereum curve ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT  time, value_eur, value_usd FROM ethereum"
    }
   ]
  },
  {
   "title": "Total row in Ethereum database",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  count(time) as NB_DATA FROM ethereum"
    }
   ]
  },
  {
   "title": "Total row over last 24H",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  count(time) as NB_DATA FROM ethereum where day(time)=day(now())"
    }
   ]
  },
  {
   "title": "Ethereum stat by week",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT week(time) as NUM_SEMAINE, avg(value_eur)as Moyenne,min(value_eur) as Minimum, max(value_eur) as Maximum FROM ethereum group by NUM_SEMAINE order by NUM_SEMAINE asc"
    }
   ]
  }
 ]
}